- .travis.yml
- index.js
- package.json
- readme.md
- windows.js
This uses [ffi](https://github.com/node-ffi/node-ffi/), and some of the familiar packages (`ref` and `ref-wchar`) and adds them as dependencies.
It uses the Windows C++ APIs (via `ffi` and family).
It is all implemented in an additional `windows.js` file, that is required conditionally.
The code is commented in each part to explain how it works, as working with `ffi` and interacting with C++ via Buffers can get a bit tangled (apart from the not-so-good Windows APIs documentation).
---
**Note**: It is based on the code of the PR: https://github.com/sindresorhus/active-win/pull/6 . So it assumes that PR being merged. Nevertheless, it only changes a couple lines from the base code from that PR. So, if we need to change that PR further it won't complicate things too much.
> Add Windows support

- lib/windows.js
- readme.md
For https://github.com/sindresorhus/active-win/issues/16 it's just a case of using the already available application path for Windows.
I don't know how to replicate this for Mac and Linux though
> Add `appPath` property on Windows

- Sources/active-win/main.swift
Check attribute title of window if exist. Some application (like WhatsApp macos) doesn't has title attribute.
Before hotfix I've got error on active window of WhatsApp app (desktop on mac os): 
Fatal error: Unexpectedly found nil while unwrapping an Optional value
[1]    57782 illegal hardware instruction  .build/debug/active-win
> Handle windows with missing title on macOS

- lib/windows.js
- package.json
Package [node-ffi](https://github.com/node-ffi/node-ffi) is no longer maintained. Updated to [node-ffi-napi](https://github.com/node-ffi-napi/node-ffi-napi) which has same API.
> WARNING: The original API of node-ffi is left mostly untouched in the N-API wrapper. However, the API did not have very well-defined properties in the context of garbage collection and multi-threaded execution. It is recommended to avoid any multi-threading usage of this library if possible.
> Migrate from `ffi` module to `ffi-napi`

- lib/linux.js
Currently if a "window" with id 0 is active, executing `active-win` will fail with:
```
(node:23889) UnhandledPromiseRejectionWarning: Error: Command failed: xprop -id 0
xprop: error: Invalid window id format: 0.
```
To reproduce the error one can run `active-win` in a short interval, then run `notify-send foo` and hover over the notification, which results in the rejection.
This patch checks for a falsy `activeWindowId` and returns `undefined` in that case.
What's interesting is, that if the error occurs the cursor changes from a mousepointer to a "plus sign cursor" and only changes back to a mouse cursor if a mousebutton is clicked.
> Return `undefined` if `activeWindowId`  is falsy on Linux

- lib/linux.js
_NET_WM_NAME doesn't exist in the output results, but WM_NAME does
> Fix Linux window name logic for xterm

- Sources/active-win/main.swift
This update adds permissions prompt for MacOS Catalina to allow active-win to get window title.
> Add permission prompts for macOS Catalina

- Sources/active-win/main.swift
- index.d.ts
- index.test-d.ts
- readme.md
Using AppleScript, this PR updates the `main.swift` file to include the ability to get the browser URL for the active window if the browser is Safari, Google Chrome, or Brave. Firefox has a much more difficult implementation in AppleScript requiring additional permissions and could be added at a later date if desired.
Fixes #62, fixes #54, fixes #45, and fixes #20.
> Add `.url` property for URL of active browser tab on macOS

- lib/windows.js
- package.json
Needed the root of the UWP Applications and continually got "ApplicationFrameHost.exe". 
Introduced code to iterate through children windows of the ApplicationFrameHost.exe which will find the underlying application, and update the processname.
> Add support for Windows UWP apps

- Sources/active-win/main.swift
- index.d.ts
- index.js
- index.test-d.ts
- lib/macos.js
- readme.md
One of the significant drawbacks is the library asking for Screen Recording permissions for macOS versions 10.15 and newer. Even though the library doesn't actually record the screen, it is required to get the title of the active window. For those who do not need the window title, there should be an option to forgo the Screen Recording permission check.
- Add a `disableScreenRecordingPermission` option.
- Skip the screen recording permission check if true.
- Return an empty string as the title if true.
- https://github.com/sindresorhus/active-win/issues/88
- https://github.com/sindresorhus/active-win/pull/67
> Add `screenRecordingPermission` option

- Sources/active-win/main.swift
- index.d.ts
- readme.md
Adds URL support for other Chrome-based browsers on macOS:
- Brave Browser Beta
- Sidekick
- Opera
> Add macOS URL support for more browsers

- Sources/active-win/main.swift
- index.d.ts
- readme.md
Adds additional Chromium-based browsers for macOS to retrieve the URL of the active tab.
> Add support for Ghost Browser and WaveBox for `url` property (macOS)

- Sources/active-win/main.swift
- index.d.ts
- readme.md
This PR adds Mighty to the list of supported browsers. Starting v0.85, Mighty browser supports AppleScript commands for reading information about windows and tabs.
[Mighty](https://mightyapp.com) is a new browser that streams Google Chrome from a powerful computer in the cloud.
> Add Mighty to list of supported browsers

- Sources/active-win/main.swift
- index.d.ts
- readme.md
We're currently using AppleScript to get the URL from apps by referencing the app name in the script. I've noticed that changing the name of the browser causes this functionality to break. As an example, if I rename 'Google Chrome' to just 'Chrome' on my mac, it'll break active-win's ability to grab the URL from Chrome.
This PR uses the application bundle ids to identify the browsers capable of providing URL. It also adds Opera Beta and Developer since their names conflicted with their production release.
Fixes https://github.com/sindresorhus/active-win/issues/117
> Use app bundle ID to identify macOS browsers

- lib/linux.js
[Someone has reported on my project's issue board](https://github.com/tkainrad/keycombiner/issues/21#issue-931055902) that my application does not support Flatpak applications.
After some investigation, the problem turned out to be relatively simple. [Due to its sandbox](https://docs.flatpak.org/en/latest/sandbox-permissions.html), it is not possible to retrieve the application path for Flatpak applications. 
Currently, _active-win_ will not return any fields for such an application, because it fails with exception in `getPathByPidSync`/`getPathByPid`:
```
internal/fs/utils.js:230
throw err;
^
Error: EACCES: permission denied, readlink '/proc/3/exe'
at Object.readlinkSync (fs.js:1028:3)
at getPathByPidSync (<full-path>/active-win/lib/linux.js:80:12)
at Object.<anonymous> …
```
> Fix support for Flatpak apps

- Sources/active-win/main.swift
- index.d.ts
- readme.md
Safari Technology Preview gives you an early look at upcoming web technologies in macOS and iOS.
> Add support for Safari Technology Preview browser

- lib/windows.js
- package.json
Fixes #103 
active-win crashes on windows when called more than once. These crashes are due to use of `ref-struct-napi` which is incompatible with `ref-napi`.  Using `ref-struct-di` instead fixes this.
https://github.com/node-ffi-napi/ref-napi#incompatible-packages
> The ref-struct-napi and ref-array-napi packages have names that sound like they are compatible with this module.
> They are not, and your application will experience crashes if you use them together with ref-napi. Use ref-struct-di or ref-array-di instead.
> Fix: crashes on windows

- index.d.ts
[According to the docs this field should be a string](https://www.npmjs.com/package/active-win#:~:text=bundleId%20(string)%20%2D%20Bundle%20identifier%20(macOS%20only)).
Here's what I get when running the `activeWindow()` function on MacOS:
```ts
{
bounds: {
height: 1055,
width: 1920,
x: 0,
y: 25,
},
id: 18890,
memoryUsage: 1248,
owner: {
bundleId: "com.microsoft.VSCode",     // <---- this is a string!
name: "Code",
path: "/Applications/Visual Studio Code.app",
processId: 31111,
},
platform: "macos",
title: "index.ts — myProject",
}
```
Typescript shows this error when I try to assign this to a `Result` object:
```
(property) activeWindow.MacOSOwner.bundleId: number
Bundle identifier.
Type 'string' is not assignable to type 'number'.ts(2322)
```
> Fix TypeScript type for `bundleId`

- Sources/windows/main.cc
Allow Window if dwWindowStatus has the same value of WS_ACTIVECAPTION.
Fixes #157
> Fix issue #157

- lib/linux.js
Noticed while running this on Linux that sometimes `WM_CLIENT_LEADER(WINDOW)` is missing from `xprop` output. The code seems to take this into account with: https://github.com/sindresorhus/active-win/blob/27221e5da0a64025bdec8759605694ea84ff9f68/lib/linux.js#L38-L39
However, the named parameter `activeWindowId` is not set correctly by the caller.
This fixes the issue.
> fix: Correctly pass activeWindowId into parseLinux

- Sources/ActiveWinCLI/main.swift
- index.d.ts
- index.test-d.ts
- lib/macos.js
- readme.md
There has been issues with macOS users regarding accessibility permission. The accessibility permission is needed in order to get the complete window title. Apparently, the `screenRecordingPermission` already handles this concern so there is no need for the accessibility permission. To fix this we could just update the `if` condition but just in case, this PR just adds a new option `accessibilityPermission`.
- `accessibilityPermission: false` - disables the accessibility permission prompt.
- Add a `accessibilityPermission` option.
- Skip the accessibility permission check if true.
- #88 
- #67 
- #96
> feat: add `accessibilityPermission` option

- Sources/ActiveWinCLI/main.swift
This pull request addresses an issue where the package was incorrectly prompting for accessibility permissions even when the `disableAccessibilityPermission` option was set to `false`.
- Updated the logic in `main.swift` to ensure that the accessibility permission prompt is conditionally executed based on the `disableAccessibilityPermission` flag.
- Wrapped the `AXIsProcessTrustedWithOptions` call within an explicit if block to prevent unintended permission prompts.
The original code used a comma-separated list of conditions in an if statement, which in Swift, functions as a logical AND operator. This meant that both conditions had to be evaluated, and as long as the first condition `(!disableAccessibilityPermission)` was `true` (i.e., `disableAccessibilityPermission` was `false`), the …
> chore: fix accessibility permission check logic 🔧

- Sources/windows/main.cc
- index.d.ts
- index.test-d.ts
- readme.md
Add support for `activeWindow()` to return `clientBounds` which is the bounds of the client area of the window. 
The client area of the window does not include Nonclient Area such as the title bar, menu bar, or window frame.  
This is useful if the client position and size is used to add overlay windows and dialogs on top of the activeWindow. 
The change is only for Windows platform and only the relevant typescript definitions and tests were updated.
> Add support for client bounds without NonClient Area on Windows
